:lantern: Implements animations transitions
MitchDroid/Volley pull request #2
Opened 2017-06-27 20:26 UTC by MitchDroid

:+1:  animations transitions and first commit to recyclerView pagination

2017-06-27 20:36 UTC, Zeyad-37 requested changes

2017-06-27 20:36 UTC, Zeyad-37 commented on app/build.gradle
> +        minSdkVersion 21
Your min SDK should be 16

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/ui/userDetails/UserDetailActivity.java
> +    @BindView(R.id.userImage)
no capital letters in resource ids

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/ui/userList/GitHubUsersListAdapter.java
> +        @BindView(R.id.userImage)
not upper case letters in resource ids

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/ui/userList/GithubUserListActivity.java
> +                // Triggered only when new data needs to be appended to the list
remove comments

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/ui/userList/GitHubUsersListAdapter.java
> +    // flag for footer ProgressBar (i.e. last item of list)
remove comments

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/utils/EndlessRecyclerViewScrollListener.java
> +    // The minimum amount of items to have below your current scroll position
remove comments from all the file

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="368dp"
add to resources

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/res/layout/activity_main.xml
> +        tools:layout_editor_absoluteY="0dp"
add to resources

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/res/layout/activity_user_detail.xml
>                          android:layout_width="100dp"
add to resources

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/res/layout/item_user.xml
>                  android:layout_width="80dp"
add to resources

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/res/layout/item_user.xml
>                  android:layout_marginLeft="5dp"
add to resources

2017-06-27 20:36 UTC, Zeyad-37 commented on app/src/main/res/values/styles.xml
> +        <!-- Add this line -->
remove comment

2017-06-27 21:16 UTC, MitchDroid commented on app/src/main/java/com/globant/samples/volley/ui/userDetails/UserDetailActivity.java
> +    @BindView(R.id.userImage)
@Zeyad-37 , fixed

2017-06-27 21:16 UTC, MitchDroid commented on app/src/main/java/com/globant/samples/volley/ui/userList/GitHubUsersListAdapter.java
> +    // flag for footer ProgressBar (i.e. last item of list)
@Zeyad-37 , fixed

2017-06-27 21:16 UTC, MitchDroid commented on app/src/main/java/com/globant/samples/volley/ui/userList/GitHubUsersListAdapter.java
> +        @BindView(R.id.userImage)
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/java/com/globant/samples/volley/ui/userList/GithubUserListActivity.java
> +                // Triggered only when new data needs to be appended to the list
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/java/com/globant/samples/volley/utils/EndlessRecyclerViewScrollListener.java
> +    // The minimum amount of items to have below your current scroll position
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="368dp"
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/res/layout/activity_main.xml
> +        tools:layout_editor_absoluteY="0dp"
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/res/layout/activity_user_detail.xml
>                          android:layout_width="100dp"
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/res/layout/item_user.xml
>                  android:layout_width="80dp"
@Zeyad-37 , fixed

2017-06-27 21:17 UTC, MitchDroid commented on app/src/main/res/values/styles.xml
> +        <!-- Add this line -->
@Zeyad-37 , fixed

2017-06-28 19:03 UTC, MitchDroid commented on app/build.gradle
> +        minSdkVersion 21
@Zeyad-37 Fixed

2017-07-07 15:06 UTC, Zeyad-37 requested changes
Fix minor comments

2017-07-07 15:06 UTC, Zeyad-37 commented on app/build.gradle
> +        minSdkVersion 19
16

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/ui/userDetails/UserDetailActivity.java
> +//            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
remove commented code

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/main/res/layout/item_user.xml
> +        app:cardCornerRadius="5dp"
resources

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/main/res/layout/item_user.xml
>                      android:textSize="15sp" />
resources

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/main/res/layout/item_user.xml
>                      android:textSize="15sp" />
resources

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/main/java/com/globant/samples/volley/data/model/item/Item.java
> +    public Item(String login, Integer id, String avatarUrl, String gravatarId, String url, String htmlUrl, String followersUrl, String followingUrl, String gistsUrl, String starredUrl, String subscri
remove unused fields

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/test/java/com/globant/samples/volley/UserDetailViewModelUnitTest.java
> +        Mockito.verify(mUserReposRepository, times(1)).getRepositories("mojombo");
use anyString() instead of string literal

2017-07-07 15:06 UTC, Zeyad-37 commented on app/src/test/java/com/globant/samples/volley/UserDetailViewModelUnitTest.java
> +        mUserDetailViewModel.doActionGithubUserRepos("mojombo").subscribe(testSubscriber);
use anyString() instead of string literal

2017-07-10 17:51 UTC, merged